server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/local
    username: admin
    password: 1234
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.yaml
    default-schema: coffee
